export const userData = [
    {
      name: 'Jan',
      "Sales": "4",
    },
    {
      name: 'Feb',
      "Sales": "8",
    },
    {
      name: 'Mar',
      "Sales": "11",
    },
    {
      name: 'Apr',
      "Sales": "9",
    },
    {
      name: 'May',
      "Sales": "6",
    },
    {
      name: 'Jun',
      "Sales": "9",
    },
    {
      name: 'Jul',
      "Sales": "12",
    },
    {
        name: 'Aug',
        "Sales": "11",
      },
      {
        name: 'Sep',
        "Sales": "4",
      },
      {
        name: 'Oct',
        "Sales": "7",
      },
      
      {
        name: 'Nov',
        "Sales": "6",
      },
      {
        name: 'Dec',
        "Sales": "12",
      },
     
  ];


  export const userRows = [
    { id: 1, 
      Username: 'Anupam Mohanty', 
      avatar: "https://cricfit.com/wp-content/uploads/2021/08/Disappointed-Pakistan-Fan.jpg",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 2, 
      Username: 'Suraj Roy', 
      avatar: "https://didikebolo.com/assets/images/didi_bw14pd.png",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 3, 
      Username: 'Nikhil Barik', 
      avatar: "https://wpdaddy.com/wp-content/uploads/2020/11/thispersondoesnotexist.jpg",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 4, 
      Username: 'Ahish Panda', 
      avatar: "https://preview.redd.it/cpslext1vx971.png?auto=webp&s=a67d767ddec283c3490613cdb0b40c180a33daf6",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 5, 
      Username: 'Jhrana  Perua', 
      avatar: "https://pbs.twimg.com/media/D8dDZukXUAAXLdY.jpg",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 6, 
      Username: 'SOmehing Nothing', 
      avatar: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6rCZOAPjOZ5_hkaro0VA1X69AzpRuNTs3dw&usqp=CAU",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 7, 
      Username: 'Everything Nothing', 
      avatar: "https://images.unsplash.com/photo-1566275529824-cca6d008f3da?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cGhvdG98ZW58MHx8MHx8&w=1000&q=80",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 8, 
      Username: 'Narendra Modi', 
      avatar: "https://pbs.twimg.com/profile_images/1479443900368519169/PgOyX1vt_400x400.jpg",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 9, 
      Username: 'Yogi Ji ', 
      avatar: "https://i0.wp.com/www.opindia.com/wp-content/uploads/2021/09/Yogi-CM-e1632060659378.jpg?fit=1000%2C655&ssl=1",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 10, 
      Username: 'German Sheperd', 
      avatar: "https://m.economictimes.com/thumb/msid-88603665,width-1200,height-900,resizemode-4,imgsize-23112/rahul-gandhi-ap.jpg",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 11, 
      Username: 'Mark Zukerbergs', 
      avatar: "https://img.jagranjosh.com/imported/images/E/GK/mark-zuckerberg-biography%20(1).jpg",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 12, 
      Username: 'Mukesh Ambani', 
      avatar: "https://akm-img-a-in.tosshub.com/indiatoday/images/reporter/202107/Mukesh_Ambani__Indian_Business-1200x768.jpg?6KLhIiJZFIemLUkNZIh.rN7RtE5__8nw",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 13, 
      Username: 'Harshad Meheta', 
      avatar: "https://upload.wikimedia.org/wikipedia/commons/7/73/Harshad_Mehta.jpg",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 14, 
      Username: 'Ratan Tata', 
      avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Ratan_Tata_photo.jpg/220px-Ratan_Tata_photo.jpg",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
    { id: 15, 
      Username: 'Jarvis Ok', 
      avatar: "https://i.pinimg.com/originals/4f/75/d1/4f75d1035914f8c4afba1f3d0e455153.png",
      "idcard": 1234456789,
      email: "anup@gmail.com",
      transaction: "1,20,000"
    },
  ];

  export const productRows = [
    { id: 1, 
      name: 'Levis Pants', 
    "Price From": "₹ 2555",
      img: "https://logos-marcas.com/wp-content/uploads/2020/04/Levi%E2%80%99s-emblema.png",
      "barNum": 1234,
      status: "Available",
      
    },
    { id: 2, 
      name: 'Jockey T-Shirts', 
    "Price From": "₹ 555",
      img: "https://brandslogo.net/wp-content/uploads/2013/03/jockey-underwear-vector-logo.png",
      "barNum": 123,
      status: "Available",
      
    },
    { id: 3, 
      name: 'Louis Phillips Pants', 
    "Price From" :"₹ 3555",
      img: "https://3.bp.blogspot.com/-ewmsV-0cw4U/XCYNomSUgHI/AAAAAAAALG4/VFFt89Fbq9s_K3H834DrH8Nf7KnGi71CwCLcBGAs/s1600/DD.jpg",
      "barNum": 1235,
      status: "Available",
      
    },
    { id: 4, 
      name: 'Jack & Jones', 
    "Price From": "₹ 2855",
      img: "https://www.ambiencemalls.com/logos/07-04-02am_08-11-2019-jack_and_jones.jpg",
      "barNum": 123,
      status: "Available",
      
    },
    { id: 5, 
      name: 'Wranngler', 
    "Price From": "₹ 2455",
      img: "https://logos-download.com/wp-content/uploads/2016/04/Wrangler_logo_and_slogan_Born_Ready.png",
      "barNum": 1239,
      status: "Not Available",
      
    },
    { id: 6, 
      name: 'GAS', 
    "Price From": "₹ 7555",
      img: "https://logos-download.com/wp-content/uploads/2016/11/GAS_Jeans_logo_wordmark.png",
      "barNum": 1243,
      status: "Not Available",
      
    },
    { id: 7, 
      name: 'Benetton', 
    "Price From": "₹ 1555",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Benetton_Group_logo.svg/2560px-Benetton_Group_logo.svg.png",
      "barNum": 1023,
      status: "Available",
      
    },
    { id: 8, 
      name: 'Gucci', 
    "Price From": "₹ 9555",
      img: "https://www.pngall.com/wp-content/uploads/11/Gucci-PNG-Photo.png",
      "barNum": 1423,
      status: "Not Available",
      
    },
    { id: 9, 
      name: 'Crocodile', 
    "Price From": "₹ 955",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRgOyqV-lOFqf4s4Dxhq7M5Uv5L_E0P-xK_AmUbq5Gj3jgmzHUIaFxvLo0tDb0ONmlwVE&usqp=CAU",
      "barNum": 123456,
      status: "Available",
      
    },
    { id: 10, 
      name: 'Lacoste', 
    "Price From": "₹ 6555",
      img: "https://www.nicepng.com/png/detail/48-488350_lacoste-logo-png-download-lacoste-logo.png",
      "barNum": 1293,
      status: "Not Available",
      
    },
    { id: 11, 
      name: 'Twills', 
      "Price From": "₹ 1755",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMWORwDS9BTsLFf13fp4E6o38pDIqOcpB8-GAAkMJVF2rLnC79hJXS2qjVLcE44lgy8U&usqp=CAU",
      "barNum": 12523,
      status: "Available",
      
    },
    { id: 12, 
      name: 'Nothing', 
     "Price From": "₹ 1555",
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Nothing_logo.svg/2560px-Nothing_logo.svg.png",
      "barNum": 15623,
      status: "Not Available",
      
    }
  ];